# one hot Encoding

# bag of words

In [1]:
import numpy as np 
import pandas as pd

In [3]:
df =pd.DataFrame({'text':['people watch campusx','campusx wath campusx','people write comment','campusx write comment',],'output':[1,1,0,0]})

In [4]:
df

text  output
0   people watch campusx       1
1   campusx wath campusx       1
2   people write comment       0
3  campusx write comment       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer()

In [10]:
bow =cv.fit_transform(df['text'])

In [11]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'wath': 4, 'write': 5, 'comment': 1}


In [14]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0 0]]
[[2 0 0 0 1 0]]


In [15]:
cv.transform(['campusx watch and write comment']).toarray()

array([[1, 1, 0, 1, 0, 1]], dtype=int64)

# N-gram/Bi-grams/Tri-grams

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

In [18]:
bow =cv.fit_transform(df['text'])

In [19]:
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'wath': 13, 'campusx wath': 1, 'wath campusx': 14, 'campusx wath campusx': 2, 'write': 15, 'comment': 5, 'people write': 9, 'write comment': 16, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [20]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0]]


# Tf-idf

In [21]:
df

text  output
0   people watch campusx       1
1   campusx wath campusx       1
2   people write comment       0
3  campusx write comment       0

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [31]:
tfidf.fit_transform(df['text']).toarray()

array([[0.44809973, 0.        , 0.55349232, 0.70203482, 0.        ,
        0.        ],
       [0.78722298, 0.        , 0.        , 0.        , 0.61666846,
        0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.        ,
        0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.        ,
        0.61366674]])

In [33]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.91629073 1.91629073 1.51082562]
['campusx' 'comment' 'people' 'watch' 'wath' 'write']
